name: eisenhower_matrix
description: The Eisenhower matrix app for all platforms! (android, ios, linux, windows, mac os, web)

publish_to: 'none'
version: 3.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  freezed_annotation: any
  firebase_storage: any
  flutter_slidable: any
  cupertino_icons: any
  cloud_firestore: any
  google_sign_in: any
  github_sign_in: any
  flutter_cubit: any
  firebase_auth: any
  firebase_core: any
  path_provider: any
  connectivity: any
  equatable: any
  cubit: any
  hive: any

dependency_overrides:
  dartx: ^0.4.2

dev_dependencies:
  flutter_launcher_icons: any
  build_runner: any
  pedantic: any
  freezed: any
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


flutter_icons:
  android: true
  ios: true
  image_path: "assets/launch_icons/icon.jpg"
